### ISSUE TITLE
ガード条件に定義されていない型を指定すると間違った中間語にコンパイルされてしまう

### ISSUE THREAD

**Issue by y-tsune** [lmntal/lmntal-compiler#8]
以下のプログラムをLaViTを使ってコンパイル、実行したところ予想の挙動と異なるものであった。

LaViTのバージョンは
LaViT
Version : 2.8.7
Date : 2015/04/06

LMNtal Compiler 1.42 (2015-04-06)
SLIM : 2.2.6
UNYO UNYO : 1.1.1 (2010/03/07)

である。
次のプログラムはコンパイルエラーになる。ただし、NullPointerExceptionであった。

```
a($x) :- hoge($x) | b($x).
```

エラーの内容は以下である。

```
java.lang.NullPointerException
    at compile.RuleCompiler.lhsatomToPath(Unknown Source)
    at compile.RuleCompiler.getLinkPath(Unknown Source)
    at compile.RuleCompiler.updateLinks(Unknown Source)
    at compile.RuleCompiler.compile_r(Unknown Source)
    at compile.RuleCompiler.compile(Unknown Source)
    at compile.RulesetCompiler.processMembrane(Unknown Source)
    at compile.RulesetCompiler.processMembrane(Unknown Source)
    at compile.RulesetCompiler.compileMembraneToGeneratingMembrane(Unknown Source)
    at compile.RulesetCompiler.compileMembrane(Unknown Source)
    at runtime.FrontEnd.run(Unknown Source)
    at runtime.FrontEnd.run(Unknown Source)
    at runtime.FrontEnd.main(Unknown Source
```

次のプログラムをコンパイルすると、間違った中間語にコンパイルされ、実行できてしまう。

```
a(x).
a($x) :- hoge($x) | b.
```

中間語は以下の通りである。

```
Compiled Ruleset @602 
Compiled Rule 
    --atommatch:
        spec           [2, 2]
    --memmatch:
        spec           [1, 1]
        jump           [L135, [0], [], []]
    --guard:L135:
        spec           [1, 1]
        jump           [L128, [0], [], []]
    --body:L128:
        spec           [1, 5]
        commit         ["_init", 0]
        loadruleset    [0, @601]
        newatom      [1, 0, 'x'_1]
        newatom      [2, 0, 'a'_1]
        alloclink    [3, 1, 0]
        alloclink    [4, 2, 0]
        unifylinks     [3, 4, 0]
        proceed        []


Compiled Ruleset @601 
Compiled Rule 
    --atommatch:
        spec           [2, 3]
    --memmatch:
        spec           [1, 3]
        findatom     [1, 0, 'a'_1]
        commit         ["_axho", 0]
        removeatom     [1, 0, 'a'_1]
        newatom      [2, 0, 'b'_0]
        freeatom       [1]
        proceed        []


Inline

```

slimによる実行結果は以下である。

```
> slim --hl tutori.il
b. x(a). @5. 
```

**Comment by 8q** [comment]
以下コミットで修正済み

https://github.com/lmntal/lmntal-compiler/commit/05ab07ef694b341722e7675944ec185e6ef769cc#diff-1ae8078bd36314c52364dbc53860a3e2
